name: dev-env-init
on: [push]

env:
  TESTING_REPO_URL: https://github.com/DataSentics/dbx-deploy.git
  TESTING_REPO_DIR: dbx-deploy

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'DataSentics/dbx-deploy'
          path: 'dbx-deploy'
      - name: Init
        run: |
          wget --quiet -O Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          cd $TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ./env-init.sh
          ./run_tests.sh

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'DataSentics/dbx-deploy'
          path: 'dbx-deploy'
      - name: Conda installation
        run: |
          powershell -Command "Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe -OutFile Miniconda3-latest-Windows-x86_64.exe"
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        shell: cmd
      - name: Init
        run: |
          source ~/Miniconda3/etc/profile.d/conda.sh
          PATH=$HOME/Miniconda3/Scripts:$PATH
          cd $TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ./env-init.sh
          ./run_tests.sh
        shell: sh {0}

  Windows_CondaNotOnPath:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'DataSentics/dbx-deploy'
          path: 'dbx-deploy'
      - name: Conda installation
        run: |
          powershell -Command "Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe -OutFile Miniconda3-latest-Windows-x86_64.exe"
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        shell: cmd
      - name: Init
        run: |
          source ~/Miniconda3/etc/profile.d/conda.sh
          cd $TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ./env-init.sh
          ./run_tests.sh
        shell: sh {0}

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          repository: 'DataSentics/dbx-deploy'
          path: 'dbx-deploy'
      - name: Init
        run: |
          brew install libgit2
          curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh --silent -o Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x Miniconda3-latest-MacOSX-x86_64.sh
          bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
          source ~/miniconda/etc/profile.d/conda.sh
          cd $TESTING_REPO_DIR
          ENV_INIT_BRANCH=${GITHUB_REF:11} ./env-init.sh
          conda activate "$PWD/.venv"
          ./run_tests.sh
          ./pylint.sh
          source $HOME/.poetry/env
          poetry add exponea-python-sdk="0.1.*"
          pip uninstall -y exponea-python-sdk
          ./env-init.sh
          ./run_tests.sh
